# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist1_joint
      - wrist2_joint
      - gripper_to_arm_joint
    action_ns: follow_joint_trajectory #Added (Ben May)
    default: true #Added (Ben May)

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - arm1_to_gripperbody_joint
    action_ns: follow_joint_trajectory #Added (Ben May)
    default: false #Added (Ben May)